# SPDX-FileCopyrightText: 2026 Chelsea Liekhus-Schmaltz and Johnathon Barhydt
#
# SPDX-License-Identifier: AGPL-3.0-only

from typing import Protocol, runtime_checkable

from core.contracts.auth import UserId
from core.contracts.users import User


@runtime_checkable
class UserRepository(Protocol):
    async def create(self, user: User) -> User: ...
    async def get(self, user_id: UserId) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def get_by_username(self, username: str) -> User | None: ...
    async def get_by_identifier(self, identifier: str) -> User | None: ...
    async def update(self, user: User) -> User: ...
    async def delete(self, user_id: UserId) -> None: ...
    async def search(self, query: str, *, limit: int = 50) -> list[User]: ...
